version: '3.8'

services:  
  web:
    build: ./app
    image: java_back
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
      
    depends_on:
      - db
      
      
  db:
  
    restart: always
    
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres 
      
    volumes:
      - sample_db:/var/lib/postgresql/data
      
volumes:
  sample_db:
    

